packages:
  - chrome-extension
  - pages/*
  - packages/*
  - tests/*
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - edgedriver
  - esbuild
  - geckodriver
  - unrs-resolver
patchedDependencies:
  '@electric-sql/pglite@0.3.14': patches/@electric-sql__pglite@0.3.14.patch
